apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: zenstats
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: zenstats
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
