apiVersion: v1
kind: Service
metadata:
  name: zenstats-api
  namespace: zenstats
  labels:
    app.kubernetes.io/name: zenstats-api
    app.kubernetes.io/part-of: zenstats
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zenstats-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
